
version: '3.8'

services:
  matchbox-server:
    image: rust:1.70
    container_name: matchbox-signaling
    command: >
      sh -c "cargo install matchbox_server && 
             matchbox_server --port 3536 --public-ip 0.0.0.0"
    ports:
      - "3536:3536"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - matchbox-network

  matchbox-p2p-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matchbox-p2p-demo
    depends_on:
      - matchbox-server
    ports:
      - "8080:8080"
    environment:
      - MATCHBOX_SERVER_URL=ws://matchbox-server:3536/game_room
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - matchbox-network

  nginx:
    image: nginx:alpine
    container_name: matchbox-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - matchbox-p2p-demo
    restart: unless-stopped
    networks:
      - matchbox-network

networks:
  matchbox-network:
    driver: bridge
